name: Deploy to prod server

on:
  push:
    branches: [ "main" ]

jobs :
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get lattest code
        uses: actions/checkout@v4

      - name:  go into tailscale network
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci 
      - name: setting up for push to non ssl local repo
        run: |
          echo '{"insecure-registries": ["${{ secrets.REGISTRY_IP }}:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: build and push to local repo
        run: |
          docker build -t ${{ secrets.REGISTRY_IP }}:5000/incanedible-be:latest .
          docker push ${{ secrets.REGISTRY_IP }}:5000/incanedible-be:latest